language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install tox-travis wheel

script:
  - tox

after_success:
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  user: sobolevn
  password: $PYPI_PASSWORD  # password is hidden
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"

notifications:
  email:
    on_success: never
    on_failure: change
