language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install

script:
    - poetry run flake8 dump-env tests
    - poetry run mypy dump_env
    - poetry run pytest
    - poetry check
    - poetry run pip check
    - poetry run safety check --bare --full-report

after_success:
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  user: sobolevn
  password: $PYPI_PASSWORD  # password is hidden
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"

notifications:
  email:
    on_success: never
    on_failure: change
